name: Static analysis

on: [pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build ccache wget gnupg lsb-release software-properties-common
          wget -q https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22 all
          rm llvm.sh
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
          create-symlink: true
      - name: Configure
        run: >
          cmake -S . -B build
          -GNinja
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CC: clang-22
          CXX: clang++-22
      - uses: aobolensk/clang-tidy-action@v1
        id: review
        name: Run clang-tidy
        with:
          build_dir: build
          exclude: "3rdparty build"
          clang_tidy_version: "22"
      - if: steps.review.outputs.total_comments > 0
        run: |
          echo "clang-tidy run has failed. See 'Run clang-tidy' stage logs"
          exit 1
